# Generated by Django 4.1.4 on 2022-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticket',
            name='price_for_one_passenger',
            field=models.PositiveIntegerField(default=1, verbose_name='Price for 1 Passenger'),
        ),
    ]
