# Generated by Django 4.1.5 on 2023-02-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flightticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination',
            new_name='_destination',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flight_number',
            new_name='_flight_number',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin',
            new_name='_origin',
        ),
        migrations.RenameField(
            model_name='flightticket',
            old_name='id',
            new_name='_id',
        ),
    ]
