# Generated by Django 4.1.4 on 2022-12-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_airline_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='register_number',
            field=models.BigIntegerField(unique=True, verbose_name='Register Number'),
        ),
    ]
