# Generated by Django 4.1.5 on 2023-02-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_alter_airplane_name_alter_airplane_register_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
