# Generated by Django 4.1.4 on 2022-12-23 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate', '0001_initial'),
        ('residence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelroomrate',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_room_rate', to='residence.hotelroom'),
        ),
        migrations.AddField(
            model_name='hotelroomrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelrate',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_rate', to='residence.hotel'),
        ),
        migrations.AddField(
            model_name='hotelrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
