# Generated by Django 4.1.4 on 2022-12-25 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0004_alter_hotel_id_alter_hotel_name_alter_hotelroom_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air', '0003_alter_airplane_name_alter_airplane_register_number'),
        ('rate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrate',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_rate', to='residence.hotel'),
        ),
        migrations.AddField(
            model_name='hotelroomrate',
            name='hotel_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_room_rate', to='residence.hotelroom'),
        ),
        migrations.AddField(
            model_name='residentialrate',
            name='residential',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='residence.residential'),
        ),
        migrations.AlterField(
            model_name='hotelrate',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='hotelroomrate',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='residentialrate',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='AirlineRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='air.airline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
