# Generated by Django 4.1.4 on 2022-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residential',
            name='price_for_one_night',
            field=models.PositiveIntegerField(default=1, verbose_name='Price for 1 Night'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='price_for_one_night',
            field=models.PositiveIntegerField(default=1, verbose_name='Price for 1 Night'),
        ),
    ]
