# Generated by Django 4.1.4 on 2022-12-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0002_residential_price_for_one_night_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='price_for_one_night',
        ),
        migrations.RemoveField(
            model_name='residential',
            name='price_for_one_night',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='price_per_night',
            field=models.PositiveIntegerField(default=1, verbose_name='Price per Night'),
        ),
        migrations.AddField(
            model_name='residential',
            name='price_per_night',
            field=models.PositiveIntegerField(default=1, verbose_name='Price per Night'),
        ),
    ]
