# Generated by Django 4.1.4 on 2022-12-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0003_remove_hotelroom_price_for_one_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='residential',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='residential',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
