# Generated by Django 4.1.5 on 2023-02-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0004_alter_hotel_id_alter_hotel_name_alter_hotelroom_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroom',
            old_name='hotel',
            new_name='_hotel',
        ),
        migrations.RenameField(
            model_name='hotelroom',
            old_name='id',
            new_name='_id',
        ),
    ]
