# Generated by Django 4.1.5 on 2023-02-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0006_rename__hotel_hotelroom_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential',
            name='residential_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='residential_category', to='residence.residentialcategory'),
        ),
    ]
