# Generated by Django 4.1.4 on 2022-12-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airlinecomment',
            old_name='comment',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='airportcomment',
            old_name='comment',
            new_name='airport',
        ),
        migrations.RenameField(
            model_name='hotelcomment',
            old_name='comment',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='hotelroomcomment',
            old_name='comment',
            new_name='hotel_room',
        ),
        migrations.RenameField(
            model_name='residentialcomment',
            old_name='comment',
            new_name='residential',
        ),
    ]
