# Generated by Django 4.1.5 on 2023-01-17 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_hotelroomreservation_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticketreservation',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='flightticketreservation',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='flightticketreservation',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelroomreservation',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelroomreservation',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelroomreservation',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='residentialreservation',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='residentialreservation',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='residentialreservation',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flightticketreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residentialreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
