# Generated by Django 4.1.5 on 2023-02-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0007_alter_residential_residential_category'),
        ('reservation', '0003_flightticketreservation_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialreservation',
            name='residential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='residential', to='residence.residential'),
        ),
    ]
